[package]
name = "horse-ai-analytics-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
shuttle-actix-web = "0.38.0"
shuttle-runtime = "0.38.0"
shuttle-secrets = "0.38.0"
tokio = "1.36.0"
async-graphql = "7.0.1"
async-graphql-actix-web = "7.0.1"
