[package]
edition = "2021"
name = "horse-ai-analytics-api"
version = "0.1.0"

[dependencies]
actix-web = "4.5.1"
async-graphql = "7.0.1"
async-graphql-actix-web = "7.0.1"
oauth2 = "4.4.2"
google-oauth = "1.10.1"
shuttle-actix-web = "0.38.0"
shuttle-runtime = "0.38.0"
shuttle-secrets = "0.38.0"
tokio = "1.36.0"
mongodb = "2.8.1"
serde = { version = "1.0.197", features = ["derive"] }
jsonwebtoken = "9"
chrono = "0.4.34"
